# Generated by Django 3.2.12 on 2023-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='field',
            field=models.CharField(choices=[('All in One', 'Tout en un'), ('Air Conditioner', 'Climatisation'), ('Carpentry', 'Menuiserie'), ('Electricity', 'Électricité'), ('Gardening', 'Jardinage'), ('Home Machines', 'Appareils ménagers'), ('House Keeping', 'Entretien ménager'), ('Interior Design', 'Design intérieur'), ('Locks', 'Serrures'), ('Painting', 'Peinture'), ('Plumbing', 'Plomberie'), ('Water Heaters', 'Chauffe-eau')], max_length=70),
        ),
    ]
