# Generated by Django 3.2.12 on 2023-09-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
        ('services', '0003_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='field',
            field=models.CharField(choices=[('Air Conditioner', 'Climatisation'), ('Carpentry', 'Menuiserie'), ('Electricity', 'Électricité'), ('Gardening', 'Jardinage'), ('Home Machines', 'Appareils ménagers'), ('House Keeping', 'Entretien ménager'), ('Interior Design', 'Design intérieur'), ('Locks', 'Serrures'), ('Painting', 'Peinture'), ('Plumbing', 'Plomberie'), ('Water Heaters', 'Chauffe-eau')], max_length=30),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('service_hours', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
